name: Deploy Next.js Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_PASSWORD }}
        script: |
          # Navigate to the project directory
          cd /var/www/frontend/stein-frontend-dev
          
          # Pull latest changes
          git pull origin main
          
          # Install dependencies (will skip if no changes in package.json)
          npm install --f
          
          # Create/update environment file
          cat > .env.local << EOF
          NEXT_PUBLIC_STRAPI_URL=https://yourdomain.com/api
          EOF
          
          # Build Next.js
          npm run build
          
          # Restart PM2 process
          pm2 restart nextjs || pm2 start npm --name "nextjs" --cwd /var/www/frontend/stein-marine-dev -- start
          
          # Save PM2 configuration
          pm2 save
